### ISSUE TITLE
Fuel, Ego planners compatibility 

### ISSUE THREAD

**Issue by FPSychotic** [ZJU-FAST-Lab/EVA-planner#1]
Hi, is it possible compile the three planners and can use them without smash the the others, would be nice as they are complementary of each other, but when I have active EVA, ROS cannot find the FUEL .launch file of plan_manage in example.
If I put them in the same catkin workspace, what will happen?
I'm scary to try because it was very hard make them work all of them. My knowledge is quite limited.
Thanks by share your work, I wish you the best of the success.

**Comment by SamuraiChamploo** [comment]
Can you describe the problem you encountered in more detail? Because I don't remember there is FUEL.launch in my code

**Comment by FPSychotic** [comment]
I wanted say FUEL's launch.
