### ISSUE TITLE
The drone is not avoiding the simulator obstacle

### ISSUE THREAD

**Issue by maulanaazhari** [ZJU-FAST-Lab/EVA-planner#2]
Hi, thanks for open-sourcing this repo!

I have one problem when running this repo with its default simulation. The drone is not avoiding the obstacle. There is no local_map  published in the /map_generator/local_cloud topic.

![image](https://user-images.githubusercontent.com/26515714/220251314-108aada4-1342-4773-aee0-cf24268c88c0.png)
![image](https://user-images.githubusercontent.com/26515714/220251382-d503edd5-e096-45e8-b382-e78de96e2fe2.png)
.
.
the data published in the /sdf_map/esdf is shown in the figure below:
![image](https://user-images.githubusercontent.com/26515714/220251909-48623045-1924-4333-bf68-d57fd8000f5b.png)
.
.
this is the output of **rqt_graph**
![image](https://user-images.githubusercontent.com/26515714/220252727-bed179b5-7ce8-424d-a370-4a1ae7531234.png)
.
I don't see the map sent to the **/adaptive_planner_node** here

**Comment by Ruanpe** [comment]
@maulanaazhari 我遇到了同样的问题，请问您解决了吗

**Comment by Zhu-w** [comment]
> @maulanaazhari 我遇到了同样的问题，请问您解决了吗

解决了

**Comment by SamuraiChamploo** [comment]
i have fixed it, please check the latest branch
