### ISSUE TITLE
The reference papers of the EDTEnvironment and the SDFMap

### ISSUE THREAD

**Issue by zorosmith** [ZJU-FAST-Lab/EVA-planner#4]
hello, i am digging deep into this repository. 
Nice work!
I am intersted in the principle of the EDTEnvironment and the SDFMap.
Could you offer some reference papers of these modules?
Thx!

**Comment by wangtiehao2010** [comment]
same question! Looking forward to your reply! Thx!

**Comment by SamuraiChamploo** [comment]
you can follow another work named [FIESTA](https://github.com/HKUST-Aerial-Robotics/FIESTA).
